port = 'PORT'

[log]
__name = 'LOG_STREAMS'
__format = 'json'

[database]
dialect = 'DATABASE_DIALECT'
host = 'DATABASE_HOST'
port = 'DATABASE_PORT'
database = 'DATABASE_NAME'
user = 'DATABASE_USER'
password = 'DATABASE_PASSWORD'

[google]
client_id = 'GOOGLE_CLIENT_ID'
client_secret = 'GOOGLE_CLIENT_SECRET'

[auth]
allowed_emails = 'AUTH_ALLOWED_EMAILS'

