port = 8081

name = 'gnl-graphql'

[[log]]
level = 'info'
out = 'stdout'

[database]
dialect = 'postgres'
host = 'xxx'
port = 5432
database = 'postgres'
username = 'xxx'
password = 'xxx'
ssl = true
[database.dialectOptions]
ssl = true

[auth]
allowed_emails = 'e@mail.com bee@mail.com'

