[[log]]
level = 'error'
out = 'stdout'

[database]
dialect = 'postgres'
host = 'localhost'
port = 5432
database = 'gnl_test'
username = 'gnl'
password = ''

[google]
client_id = 'GOOGLE_CLIENT_ID'
client_secret = 'GOOGLE_CLIENT_SECRET'

